// cloudcore.js — Phase 4 clouds core (round 15). CONCEPT §8: "coverage is a
// field, volume is a look." This module is the FIELD half plus every JS twin:
//
//  - Coverage/type is a coarse planetary raster: a 256x128 equirect per
//    (body, deck, keyframe), generated by DIRECT per-texel evaluation of a
//    closed-form cov(direction, keyframe) — the bakeDiscMap precedent; no
//    intermediate grid, no resample, ONE source of truth for GPU + JS + tests.
//  - Time enters the ROADMAP [time-field] way: recipe-declared keyframes
//    (k = floor(t / keyframeH·3600), pure fn of t), a FIXED deterministic
//    interpolation (linear lerp by frac, done identically in GLSL and here),
//    and advected patterns evaluated in closed-form DRIFTED coordinates (the
//    sample direction rotates about the spin axis by the deck's drift phase,
//    computed in DOUBLE on the CPU per frame — never face-local uv, never a
//    float32 world-time product). No stepped weather state exists anywhere.
//  - Adjacent keyframes are CORRELATED evolutions of ONE field (pre-code
//    panel F1/H3: independent per-k draws crossfade into a variance collapse
//    — "keyframe breathing", spatial contrast 0.71x at every mid-frac): the
//    fbm sample coordinate advances by k·evolve along a fixed diagonal, so
//    the lerp interpolates two nearby slices of one continuous pattern.
//    test:cloud pins the mid-frac variance ratio >= 0.9.
//  - The moisture term is an ANOMALY (panel F3: over open ocean the advected
//    moisture grid saturates to EXACTLY the zonal prior — a DC duplicate):
//    moist(d) − prior(lat) carries only real coastal/orographic geography
//    and is zero over homogeneous ocean by construction.
//  - The vertical profile is EXACTLY mean-1 over the deck (panel F2: an
//    unnormalized bump made the marched cloud thinner than its shadow):
//    h(x) = 6x(1−x) with antiderivative H(x) = x²(3−2x) (= smoothstep), so
//    every rung and the shadow share one column optical depth by law.
//  - detail = 1 + detailAmp·fbm3 with detailAmp <= 1 ENFORCED (fbm3 is
//    bounded in [−1,1]): strictly positive, exactly mean-1 — no clamp
//    rectification (panel F2b).
//
// Generation runs in the WORKER ('clouds' message — panel H1: a cold
// main-thread [global] build measures ~3.3 s); Node tests import this module
// directly. All noise through mathx (bit-exact hashi/noise3/fbm3).

import { clamp, smoothstep, fbm3, latOf } from './mathx.js';

// 512x256 equirect (texel ~78 km): at the blue-marble disc scale a texel is
// ~1.2 px, so the near-binary remapped field's edges land at pixel scale —
// the 256-wide first cut staircased visibly (anchor-tier probe). Generation
// is worker-side; x4 cost is ~200-400 ms per keyframe pair.
export const CLOUD_W = 512;
export const CLOUD_H = 256;
export const MAX_DECKS = 2;
export const MAX_BODY_SLOTS = 4; // matches the §11 disc atlas rows

// ---------------------------------------------------------------------------
// laws shared by every consumer (GLSL twins live in shaders.js COMMON)

// zonal cloudiness prior, normalized to [0,1] — the SAME ITCZ/subtropic shape
// the moisture pass uses (globalgrid prior = 0.75 + 0.25·cos(6·lat)), so
// clouds and rain agree by shared form, not by tuning.
export const zonalCloud = (lat) => 0.5 + 0.5 * Math.cos(6 * lat);

// moisture prior as baked into the [global] moist grid (globalgrid.js:604).
// The anomaly subtracts it back out: open ocean → exactly 0.
export const moistPrior = (lat) => 0.75 + 0.25 * Math.cos(6 * lat);

// normalized vertical profile over the deck: x = (alt − base)/thick in [0,1].
// mean over [0,1] is EXACTLY 1; H is its antiderivative (H(1)=1).
export const profileH = (x) => {
  const c = clamp(x, 0, 1);
  return c * c * (3 - 2 * c);
};
export const profileh = (x) => {
  const c = clamp(x, 0, 1);
  return 6 * c * (1 - c);
};
// column mean of h over an altitude span [x0,x1] (order-free); degenerates to
// h(mid) as the span collapses (H' = h — the same law, one scale down).
export function columnMean(x0, x1) {
  const a = clamp(Math.min(x0, x1), 0, 1), b = clamp(Math.max(x0, x1), 0, 1);
  if (b - a < 1e-4) return profileh(0.5 * (a + b));
  return (profileH(b) - profileH(a)) / (b - a);
}

// ---------------------------------------------------------------------------
// the coverage field: closed-form cov(direction, deck recipe, keyframe k).
// `moistAt` is a sampler (dir → moist in [0,1]) or null for bodies without a
// [global] moisture grid (the Rubra fallback — zonal + fbm only, panel G7).
export function covAt(dir, deck, seed, k, moistAt, season) {
  const lat = latOf(dir);
  // correlated keyframe evolution: ONE fbm field, coordinate advanced k·evolve
  // along a fixed diagonal (unit-ish, incommensurate components so the walk
  // never revisits a lattice period). No ⊕k reseed — see the panel note above.
  const ev = (deck.evolve ?? 0.3) * k;
  const f = deck.freq ?? 5.0;
  const w = fbm3(
    dir[0] * f + ev * 0.7071,
    dir[1] * f + ev * 0.5253,
    dir[2] * f - ev * 0.4788,
    seed, deck.oct ?? 4,
  );
  let raw = (deck.cov0 ?? 0.2)
    + (deck.zonalW ?? 0.25) * zonalCloud(lat)
    + (deck.fbmW ?? 0.55) * w;
  if (moistAt && (deck.moistW ?? 0) !== 0) {
    // moisture ANOMALY about the field's own mid-scale (panel F3, amended by
    // measurement): with the shipped advection params (γ 0.007, 128 sweeps)
    // the ocean does NOT saturate to the prior — fetch structure is real and
    // the field's median sits near 0.4·prior. Subtracting moistMid·prior
    // keeps the coastal/fetch/rain-shadow geography, centres the term near
    // zero globally (a DC term is a duplicate of cov0), and stays closed-form.
    // test:cloud pins the global mean of this term to ±0.05.
    raw += deck.moistW * (moistAt(dir) - (deck.moistMid ?? 0.4) * moistPrior(lat));
  }
  // round 16 — seasonal WEATHER MODES (pre-code panel B). `season` = { th (orbital
  // phase angle, rad), sinDecl (subsolar-latitude sine) }, evaluated per-keyframe by
  // the CALLER (makeCloudKeyframes) and passed for k and k+1 SEPARATELY — never one
  // shared scalar, or rollover byte-continuity breaks (panel storm-season-rollover).
  // Absent season, or a deck without stormW/hoodAmp, is a no-op ⇒ Tellus / Rubra's
  // cirrus deck / Luna bake BYTE-IDENTICAL to round 15. Both terms modulate the
  // FIELD (coverage), never the look — §8 "coverage is a field, volume is a look."
  if (season) {
    if ((deck.stormW ?? 0) !== 0) {
      // global dust storm: a seasonal DC lift of THIS deck's own fbm field —
      // near-zero off-season (raw stays below covFloor ⇒ EXACTLY clear, the body's
      // normal look), pushed past covHi in-season (near-total dusty pall that casts
      // the ground shadow through the same slot). Circular orbit has no perihelion
      // distance cue (§10) so it keys on the orbital phase ANGLE alone.
      raw += deck.stormW * stormEnvelope(season.th, deck.stormLs ?? 0, deck.stormWidth ?? 0.6);
    }
    if ((deck.hoodAmp ?? 0) !== 0) {
      // winter-pole hood: the seasonalFrost SHAPE (winter = −sinLat·sinDecl) raising
      // coverage over whichever pole is in local winter. In DEEP winter the season
      // shift pulls the onset down to ~47° (inside F1's mid-lat band), like Mars's
      // real polar hood — but F1 bakes with NO season sampler, so the hood term is
      // a no-op there; it is a smooth ZONAL DC lift (no per-k noise redraw), so even
      // when exercised it cannot break the variance-ratio pin (verified post-panel).
      const sinLat = clamp(dir[1], -1, 1);
      const winter = -sinLat * season.sinDecl;
      raw += deck.hoodAmp * smoothstep(deck.hoodLatOn ?? 0.72, deck.hoodLatFull ?? 0.92,
        Math.abs(sinLat) + (deck.hoodSeasonK ?? 0.5) * winter);
    }
  }
  // bimodal remap: broken cloud/clear lanes, not gray mush (the anchor board)
  const c = smoothstep(deck.covLo ?? 0.4, deck.covHi ?? 0.62, raw);
  // hard clear floor (anchor-tier probe): the remap's low skirts (cov
  // 0.05-0.3) look clear from above but slant paths amplify them x2-8 into a
  // whole-sky veil that hides every sea gap. Below the floor the air is
  // EXACTLY clear — one law, so the rungs, the shadow, the twins and the
  // clearsky sigma(0) witness all agree by construction.
  return c < (deck.covFloor ?? 0.08) ? 0 : c;
}

// wrapped-gaussian seasonal envelope on the orbital-phase circle: 1 at the storm
// centre Ls, decaying with the shortest angular distance (width in radians). Pure
// closed-form fn of the orbital phase th — the [time-field] dust-storm gate (§8).
export function stormEnvelope(th, centerLs, width) {
  const d = Math.atan2(Math.sin(th - centerLs), Math.cos(th - centerLs)); // → [−π,π]
  const w = Math.max(width, 1e-3);
  return Math.exp(-0.5 * (d / w) * (d / w));
}

// type channel: stratiform(0) ↔ cumuliform(1) character; drives detail
// amplitude + albedo shading only (round 15 — one canonical profile shape).
export function typeAt(dir, deck, seed, k) {
  const ev = (deck.evolve ?? 0.3) * k;
  const f = (deck.freq ?? 5.0) * 0.55;
  const w = fbm3(
    dir[0] * f - ev * 0.5253,
    dir[1] * f + ev * 0.7071,
    dir[2] * f + ev * 0.4788,
    seed + 37, deck.oct ?? 4,
  );
  return clamp(0.5 + 0.5 * w, 0, 1);
}

// ---------------------------------------------------------------------------
// keyframe raster generation: 256x128 equirect, texel-center directions in
// the DISC ATLAS convention (SKY_FRAG buv: u = atan(z,x)/2π + 0.5,
// v = asin(y)/π + 0.5). Packed RGBA8: R = cov(k), G = type(k),
// B = cov(k+1), A = type(k+1) — one texture tap yields both keyframes.
export function texelDir(i, j, out = [0, 0, 0]) {
  const lon = ((i + 0.5) / CLOUD_W - 0.5) * 2 * Math.PI;
  const lat = ((j + 0.5) / CLOUD_H - 0.5) * Math.PI;
  const cl = Math.cos(lat);
  out[0] = cl * Math.cos(lon);
  out[1] = Math.sin(lat);
  out[2] = cl * Math.sin(lon);
  return out;
}

// generate BOTH keyframes (k, k+1) for every deck of a body into one packed
// Uint8Array of `decks.length` layers, layer-major (layer stride W·H·4).
// Deterministic pure fn of (body recipe, k). `moistAt` is the [global] moist
// sampler (dir → [0,1]) or null — the CALLER owns the globalgrid dependency
// (bake.worker.js / tests): this module stays main-bundle-light and the cold
// ~3.3 s grid build can never leak onto the main thread (panel H1).
export function makeCloudKeyframes(body, k, moistAt = null, seasonAt = null) {
  const decks = body.clouds?.decks ?? [];
  const n = Math.min(decks.length, MAX_DECKS);
  const rgba = new Uint8Array(n * CLOUD_W * CLOUD_H * 4);
  if (!n) return { rgba, decks: 0 };
  const moist = moistAt;
  // seasonal scalars — evaluated SEPARATELY for k and k+1 (panel storm-season-
  // rollover): B,A at keyframe k must equal R,G at keyframe k+1 byte-exact, so the
  // k+1 slice here (s1) shares the exact scalar the next message's k slice will use.
  // Unlike moistAt (legitimately k-independent, reused), a single shared season
  // scalar would shift the k+1 slice and break rollover continuity.
  const s0 = seasonAt ? seasonAt(k) : null;
  const s1 = seasonAt ? seasonAt(k + 1) : null;
  const seed0 = body.clouds.seed ?? 71;
  const d = [0, 0, 0];
  for (let L = 0; L < n; L++) {
    const deck = decks[L];
    const seed = (seed0 + L * 101) | 0;
    const base = L * CLOUD_W * CLOUD_H * 4;
    for (let j = 0; j < CLOUD_H; j++) {
      for (let i = 0; i < CLOUD_W; i++) {
        texelDir(i, j, d);
        const o = base + (j * CLOUD_W + i) * 4;
        rgba[o] = Math.round(covAt(d, deck, seed, k, moist, s0) * 255);
        rgba[o + 1] = Math.round(typeAt(d, deck, seed, k) * 255);
        rgba[o + 2] = Math.round(covAt(d, deck, seed, k + 1, moist, s1) * 255);
        rgba[o + 3] = Math.round(typeAt(d, deck, seed, k + 1) * 255);
      }
    }
  }
  return { rgba, decks: n };
}

// ---------------------------------------------------------------------------
// time plumbing (double precision, CPU only — frames.js discipline)

export const keyframeSec = (body) => (body.clouds?.keyframeH ?? 6) * 3600;
export function cloudKeyOf(body, t) {
  const tau = keyframeSec(body);
  const k = Math.floor(t / tau);
  return { k, frac: clamp(t / tau - k, 0, 1) };
}
// per-deck drift phase in [0,1): the closed-form drifted coordinate
// (lon − ω·t), ω from the recipe in degrees of longitude per 86400 s.
export function driftPhase(deck, t) {
  const w = (deck.driftDegPerDay ?? 0) / 360;
  const p = (w * t) / 86400;
  return p - Math.floor(p);
}

// ---------------------------------------------------------------------------
// JS twins of the GLSL samplers (F3-bench: the twin models the GPU — it reads
// the SAME quantized RGBA8 bytes with the same bilinear + drift arithmetic).

// rotate dir about +Y (the spin axis) by −2π·phase — the drift
export function driftDir(dir, phase, out = [0, 0, 0]) {
  const a = -2 * Math.PI * phase;
  const c = Math.cos(a), s = Math.sin(a);
  out[0] = c * dir[0] - s * dir[2];
  out[1] = dir[1];
  out[2] = s * dir[0] + c * dir[2];
  return out;
}

// bilinear sample of one packed layer at a (drifted) direction; ch pairs:
// returns { cov, type } already lerped by frac (the fixed interpolation).
export function sampleCloud(rgba, layer, dir, frac) {
  const u = Math.atan2(dir[2], dir[0]) / (2 * Math.PI) + 0.5;
  const v = Math.asin(clamp(dir[1], -1, 1)) / Math.PI + 0.5;
  let x = u * CLOUD_W - 0.5;
  let y = clamp(v * CLOUD_H - 0.5, 0, CLOUD_H - 1);
  x -= Math.floor(x / CLOUD_W) * CLOUD_W; // lon wraps
  const x0 = Math.floor(x), y0 = Math.floor(y);
  const fx = x - x0, fy = y - y0;
  const x1 = (x0 + 1) % CLOUD_W, y1 = Math.min(y0 + 1, CLOUD_H - 1);
  const base = layer * CLOUD_W * CLOUD_H * 4;
  const at = (xx, yy, c) => rgba[base + (yy * CLOUD_W + xx) * 4 + c] / 255;
  const bl = (c) =>
    (at(x0, y0, c) * (1 - fx) + at(x1, y0, c) * fx) * (1 - fy)
    + (at(x0, y1, c) * (1 - fx) + at(x1, y1, c) * fx) * fy;
  return {
    cov: bl(0) * (1 - frac) + bl(2) * frac,
    type: bl(1) * (1 - frac) + bl(3) * frac,
  };
}

// coverage at a world direction for deck L at time t — THE field twin
export function cloudCovJS(body, rgba, L, dir, t) {
  const deck = body.clouds?.decks?.[L];
  if (!deck) return 0;
  const { frac } = cloudKeyOf(body, t);
  const dd = driftDir(dir, driftPhase(deck, t));
  return sampleCloud(rgba, L, dd, frac).cov;
}

// ground shade twin: transmittance of coverage along the sun ray from point p
// (planet-centred metres) — coverage only, never the rendered cloud (CONCEPT
// §8); single tap at the deck mid-shell (adequate BECAUSE muClamp bounds the
// modeled slant path to ~thick/muClamp ≪ one raster texel — panel K2).
export function cloudShadeJS(body, rgba, p, sunDir, t) {
  const decks = body.clouds?.decks ?? [];
  if (!decks.length) return 1;
  const muClamp = body.clouds.muClamp ?? 0.09;
  const R = body.R;
  const r = Math.sqrt(p[0] * p[0] + p[1] * p[1] + p[2] * p[2]);
  let T = 1;
  for (let L = 0; L < Math.min(decks.length, MAX_DECKS); L++) {
    const deck = decks[L];
    const top = R + deck.baseM + deck.thickM;
    if (r >= top) continue;
    const Rmid = R + deck.baseM + 0.5 * deck.thickM;
    // sun-ray crossing of the mid-shell sphere (p is inside it): positive root
    const b = p[0] * sunDir[0] + p[1] * sunDir[1] + p[2] * sunDir[2];
    const c = r * r - Rmid * Rmid;
    const disc = b * b - c;
    if (disc <= 0) continue;
    const tHit = -b + Math.sqrt(disc);
    if (tHit <= 0) continue;
    const q = [p[0] + sunDir[0] * tHit, p[1] + sunDir[1] * tHit, p[2] + sunDir[2] * tHit];
    const ql = Math.sqrt(q[0] * q[0] + q[1] * q[1] + q[2] * q[2]);
    const qd = [q[0] / ql, q[1] / ql, q[2] / ql];
    const cov = cloudCovJS(body, rgba, L, qd, t);
    const mu = Math.max((qd[0] * sunDir[0] + qd[1] * sunDir[1] + qd[2] * sunDir[2]), muClamp);
    // depth remaining above p, in normalized profile units (H law — the same
    // column the march integrates; full column ⇒ exactly sigma·cov·thick/mu)
    const x0 = clamp((r - R - deck.baseM) / deck.thickM, 0, 1);
    const colAbove = (1 - profileH(x0)) * deck.thickM;
    T *= Math.exp(-(deck.sigmaK ?? 0.003) * cov * colAbove / mu);
  }
  return T;
}

// hemisphere-weighted CLOUD ALPHA mean for planetshine (panel H1 + the M3
// calibration): the mean of the DISC ALPHA LAW over cells weighted by
// max(0, cell·toReceiver)·max(0, cell·toSun) at the CURRENT drift phase —
// the lit, visible hemisphere, never the whole sphere. Averaging alpha (not
// coverage) matters: alpha saturates in cov, so alpha(mean cov) overshoots
// the disc integral by 2x on a broken field (Jensen — pinned in test:cloud).
export function alphaMeanLit(body, rgba, L, t, dirToReceiver, dirToSun) {
  const deck = body.clouds?.decks?.[L];
  if (!deck) return 0;
  const { frac } = cloudKeyOf(body, t);
  const phase = driftPhase(deck, t);
  const d = [0, 0, 0], dd = [0, 0, 0];
  let sum = 0, wsum = 0;
  for (let j = 2; j < CLOUD_H; j += 4) {
    for (let i = 2; i < CLOUD_W; i += 4) {
      texelDir(i, j, d);
      const wr = Math.max(0, d[0] * dirToReceiver[0] + d[1] * dirToReceiver[1] + d[2] * dirToReceiver[2]);
      const ws = Math.max(0, d[0] * dirToSun[0] + d[1] * dirToSun[1] + d[2] * dirToSun[2]);
      const w = wr * ws * Math.cos(((j + 0.5) / CLOUD_H - 0.5) * Math.PI);
      if (w <= 0) continue;
      driftDir(d, phase, dd);
      sum += discAlpha(deck, sampleCloud(rgba, L, dd, frac).cov) * w;
      wsum += w;
    }
  }
  return wsum > 0 ? sum / wsum : 0;
}

// disc-mix alpha law shared with SKY_FRAG's companion-disc cloud term and the
// planetshine reduction: alpha = 1 − exp(−sigma·cov·thick·2) (a vertical
// double-pass through the deck — the disc sees reflected light).
export const discAlpha = (deck, cov) =>
  1 - Math.exp(-2 * (deck.sigmaK ?? 0.003) * cov * deck.thickM);

// ---------------------------------------------------------------------------
// Phase W above-band representation (round 24). Above the declared clouds band
// the deck renders its closed-form TIME-AVERAGE — of the ALPHA law, never of
// coverage (alpha is concave in cov, so alpha(mean cov) overshoots mean(alpha):
// the round-15 planetshine Jensen lesson, now a [time-field] law). The mean is
// shipped as an EQUIVALENT COVERAGE cov* = A⁻¹(E_t[A(cov)]) packed into BOTH
// keyframe slots (R=B, G=A), so the unchanged GLSL/JS samplers — whose frac
// lerp becomes the identity — render the exact analytic mean through the same
// alpha law. Drifting decks additionally average over the drift ring (a fixed
// ground point sees its whole latitude circle), making the raster
// rotation-invariant, so a zeroed drift phase is exact, not approximate.

// invert the disc alpha law: the coverage whose alpha equals meanAlpha.
export const equivalentMeanCov = (deck, meanAlpha) => {
  const a = 2 * (deck.sigmaK ?? 0.003) * deck.thickM;
  return clamp(-Math.log(Math.max(1 - meanAlpha, 1e-12)) / a, 0, 1);
};

// the time-average spans one keyframe-evolution correlation block (MEAN_BLOCK_K
// keyframes ≈ 2 world-days at keyframeH 6) anchored at the epoch's block, so
// seasonal decks (dust storms, polar hoods) keep their epoch-local season — a
// capture at month/s shows THIS season's mean, not a washed annual gray.
export const MEAN_BLOCK_K = 8;
export const meanBlockOf = (body, t) => Math.floor(cloudKeyOf(body, t).k / MEAN_BLOCK_K);

// E over frac of alpha(lerp(c0, c1, f)): 2-point Gauss on [0,1] — fixed
// deterministic quadrature (the solver-policy law applied to an integral).
const GAUSS_F = [0.5 - 0.5 / Math.sqrt(3), 0.5 + 0.5 / Math.sqrt(3)];

export function makeCloudMeanRaster(body, block, moistAt = null, seasonAt = null) {
  const decks = body.clouds?.decks ?? [];
  const n = Math.min(decks.length, MAX_DECKS);
  const rgba = new Uint8Array(n * CLOUD_W * CLOUD_H * 4);
  if (!n) return { rgba, decks: 0, block };
  const kA = block * MEAN_BLOCK_K;
  const seed0 = body.clouds.seed ?? 71;
  // coarse evaluation grid (the mean field is smooth by construction — fbm
  // averaged over a whole evolution block), bilinearly upsampled to the atlas.
  const W2 = CLOUD_W >> 2, H2 = CLOUD_H >> 2;
  const d = [0, 0, 0];
  const covK = new Float64Array(MEAN_BLOCK_K + 1);
  const seasons = [];
  for (let k = kA; k <= kA + MEAN_BLOCK_K; k++) seasons.push(seasonAt ? seasonAt(k) : null);
  for (let L = 0; L < n; L++) {
    const deck = decks[L];
    const seed = (seed0 + L * 101) | 0;
    const meanA = new Float64Array(W2 * H2);
    const meanT = new Float64Array(W2 * H2);
    for (let j = 0; j < H2; j++) {
      for (let i = 0; i < W2; i++) {
        // coarse texel center mapped onto the fine texel-direction convention
        texelDir((i + 0.5) * 4 - 0.5, (j + 0.5) * 4 - 0.5, d);
        let tSum = 0;
        for (let k = 0; k <= MEAN_BLOCK_K; k++) {
          covK[k] = covAt(d, deck, seed, kA + k, moistAt, seasons[k]);
          const w = k === 0 || k === MEAN_BLOCK_K ? 0.5 : 1;
          tSum += w * typeAt(d, deck, seed, kA + k);
        }
        let aSum = 0;
        for (let k = 0; k < MEAN_BLOCK_K; k++) {
          for (const f of GAUSS_F) aSum += discAlpha(deck, covK[k] * (1 - f) + covK[k + 1] * f);
        }
        const o = j * W2 + i;
        meanA[o] = aSum / (MEAN_BLOCK_K * GAUSS_F.length);
        meanT[o] = tSum / MEAN_BLOCK_K;
      }
    }
    // drift-ring average: the time-mean at a fixed point of a drifting deck is
    // the lon-ring mean of alpha (linear in alpha, THEN inverted to cov*).
    if ((deck.driftDegPerDay ?? 0) !== 0) {
      for (let j = 0; j < H2; j++) {
        let aRow = 0, tRow = 0;
        for (let i = 0; i < W2; i++) { aRow += meanA[j * W2 + i]; tRow += meanT[j * W2 + i]; }
        aRow /= W2; tRow /= W2;
        for (let i = 0; i < W2; i++) { meanA[j * W2 + i] = aRow; meanT[j * W2 + i] = tRow; }
      }
    }
    // bilinear upsample in ALPHA space (the calibrated quantity), invert per
    // fine texel, pack both keyframe slots identically (frac-lerp = identity).
    const base = L * CLOUD_W * CLOUD_H * 4;
    for (let j = 0; j < CLOUD_H; j++) {
      const y = clamp(j / 4 - 0.375, 0, H2 - 1);
      const y0 = Math.floor(y), y1 = Math.min(y0 + 1, H2 - 1), fy = y - y0;
      for (let i = 0; i < CLOUD_W; i++) {
        let x = i / 4 - 0.375;
        x -= Math.floor(x / W2) * W2; // lon wraps
        const x0 = Math.floor(x) % W2, x1 = (x0 + 1) % W2, fx = x - Math.floor(x);
        const blerp = (g) => (g[y0 * W2 + x0] * (1 - fx) + g[y0 * W2 + x1] * fx) * (1 - fy)
          + (g[y1 * W2 + x0] * (1 - fx) + g[y1 * W2 + x1] * fx) * fy;
        const cov = Math.round(equivalentMeanCov(deck, blerp(meanA)) * 255);
        const typ = Math.round(clamp(blerp(meanT), 0, 1) * 255);
        const o = base + (j * CLOUD_W + i) * 4;
        rgba[o] = cov; rgba[o + 1] = typ; rgba[o + 2] = cov; rgba[o + 3] = typ;
      }
    }
  }
  return { rgba, decks: n, block };
}

// validation used by tests and tiles/recipe consumers: the panel-F2b bound.
export function assertCloudRecipe(body) {
  const decks = body.clouds?.decks ?? [];
  for (const d of decks) {
    if ((d.detailAmp ?? 0) > 1.0 + 1e-9) {
      throw new Error(`clouds: detailAmp ${d.detailAmp} > 1 breaks the mean-1 detail law (${body.id})`);
    }
    if (!(d.thickM > 0) || !(d.baseM >= 0)) throw new Error(`clouds: bad deck geometry (${body.id})`);
  }
  if (decks.length > MAX_DECKS) throw new Error(`clouds: ${decks.length} decks > MAX_DECKS (${body.id})`);
  return decks.length;
}
